# Generated by Django 5.1.6 on 2025-02-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacreada',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='tareadelalumno',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
