# Generated by Django 5.1.6 on 2025-02-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tareacreada_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareacalificada',
            name='tarea',
        ),
        migrations.AddField(
            model_name='tareacalificada',
            name='tarea_alumno',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tareas.tareadelalumno'),
            preserve_default=False,
        ),
    ]
