# Generated by Django 5.1.6 on 2025-02-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_remove_tareacalificada_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareadelalumno',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareadelalumno',
            name='archivo',
            field=models.FileField(default=1, upload_to='tareas_alumnos/'),
            preserve_default=False,
        ),
    ]
